// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"time"
)

type Feed struct {
	ID        string
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
}

type User struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ApiKey    string
}
